package:
  name: warpkit
  version: 0.0.1

source:
  path: ../ 

build:
  script: python -m pip install ./[dev] -v

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.24
    - cmake-build-extension >=0.5.1
  host:
    - julia >=1.6.3
    - python >=3.9
  run:
    - julia >=1.6.3
    - python >=3.9
