name: Build and Test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build and Test Warpkit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Julia 1.8.3
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8.3'
      - name: Add Julia shared libraries
        run: |
          echo ${RUNNER_TOOL_CACHE}/julia/$(julia -e "print(VERSION)")/x64/lib | sudo tee -a /etc/ld.so.conf.d/julia.conf
          cat /etc/ld.so.conf.d/julia.conf
          sudo ldconfig
          ldconfig -p | grep julia
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies and build
        run: |
          python -m pip install -e ./[dev] -v --config-settings editable_mode=strict
      - name: Test warpkit
        run: |
          pushd tests/data && ./download_bids_testdata.sh && popd
          python -m pytest -s -v

# https://docs.github.com/en/actions/learn-github-actions/expressions
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  # github.workflow: name of the workflow
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true
