name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test Warpkit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Julia 1.8.3
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8.3'
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies and build
        run: |
          python -m pip install -e ./[dev] -v --config-settings editable_mode=strict
      - name: Test warpkit
        run: |
          pushd tests/data && ./download_bids_testdata.sh && popd
          LD_LIBRARY_PATH=${RUNNER_TOOL_CACHE}/julia/$(julia -e "print(VERSION)")/x64/lib:${LD_LIBRARY_PATH} python -m pytest -s -v
